### ISSUE TITLE
Language test not recognized for virtuoso Version 06.01.3127

### ISSUE THREAD

**Issue by MaillPierre** [Wimmics/dekalog#2]
Query used for the language test:
ASK
        WHERE {
            SELECT DISTINCT (lang(?o) as ?lang)  WHERE {
                ?s ?p ?o
                FILTER( isLiteral(?o) )
            }
        }

returns an error at "SELECT" in the virtuoso Version 06.01.3127 used for tests.
The query works when tested in DBPedia, DBPedia-fr, WASABI.

**Comment by FabienGandon** [comment]
Hello la version SELECT passe? 

SELECT * WHERE { 
SELECT DISTINCT (lang(?o) as ?lang) WHERE { 
?s ?p ?o . FILTER( isLiteral(?o) ) 
} 
} 
LIMIT 1 

et pourquoi pas directement un ASK? 

ASK { 
?s ?p ?o 
BIND( ( lang (?o) ) AS ?lang) 
} 

peut-être n'ai-je pas compris ton but.

**Comment by MaillPierre** [comment]
Le but est d'avoir une requête pour vérifier qu'il y a au moins un tag de langage, donc ce que tu propose est bon.
Aucune des deux versions que tu a donné ne passe, ce qui est totalement irrégulier, ca doit être un problème avec le serveur. Je vais voir si je dois le mettre à jour ou si j'ai raté un réglage.

**Comment by ocorby** [comment]
Hello, 

et pourquoi pas directement un ASK? 

ASK { 
?s ?p ?o 
BIND( ( lang (?o) ) AS ?lang) 
} 

Le bind n'échoue pas, il laisse la variable unbound. 

Olivier
